export const APIKEY = 'e3f8cf1d3157390afecb809d5253663c'
export const URLBASE = ' https://api.themoviedb.org/3/'
export const PELI = 'movie'
export const SERIE = 'tv'
export const COMUN2 = '&watch_region=AR&api_key='
export const AGREGAR_VIDEOS = '&append_to_response=videos'
export const AGREGAR_STAFF = '&append_to_response=credits'
export const LENGUAJE = '&language=es-ES&api_key='
export const BUSQUEDA = 'search/'
export const CONSULTA = 'discover/'
export const COMUN = '?include_adult=false&include_video=false&language=es-ES&page=1&region=AR'
export const NUEVO = '&release_date.gte=2023-01-01&sort_by=sort_by=primary_release_date.desc'
export const MAS_VALUADAS = '&release_date.gte=2023-01-01&sort_by=vote_average.desc'
export const POPULAR = '&sort_by=vote_average.desc'
export const PROXIMO = '&sort_by=popularity.desc'
export const AIRE = '/airing_today?'
export const IMAGENES_URL_BASE = 'https://image.tmdb.org/t/p/'
export const TAMAÑO_P = 'w500'
export const TAMAÑO_G = 'original'
export const URL_YOUTUBE = 'https://www.youtube-nocookie.com/embed/'
export const OPCIONES =
    '?autoplay=1&modestbranding=1&rel=0&showinfo=0&mute=1&controls=1&cc_load_policy=3&hd=1'
export const ERROR_PETICION = 'Hubo un error al realizar la petición'
